import MainLayout from 'components/layout/main';
import { NextPageWithLayout } from 'models';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Learn Nextjs | Tim ❤️</title>
        <meta name="description" content="Generated by Quốc Cường" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{' '}
          <Link href="/about">
            <a>Next.js!</a>
          </Link>
        </h1>
      </main>
    </div>
  );
};
Home.Layout = MainLayout;
export default Home;
